### ISSUE TITLE
Link to /usr/bin

### ISSUE THREAD

**Issue by parkr** [jekyll/omnibus-jekyll#2]
You should _not_ have to modify your `$PATH` to get this to work.

**Comment by parkr** [comment]
There has to be some sort of post-install step... hm.

**Comment by alfredxing** [comment]
I would create a symlink in `/usr/bin` or `/usr/local/bin`. Or you could add a `export PATH=` line in `~/.bash_profile` (but this would only work for the current user, not all users).

**Comment by parkr** [comment]
`/usr/local/bin` would work, but I want it to work out-of-the-box. No editing of `.bash_profile` files.
